# Development pod configuration with developer-friendly permissions
# This configuration ensures all files are accessible to the developer

apiVersion: v1
kind: Pod
metadata:
  name: podserve-dev
  labels:
    app: podserve
    mode: development
spec:
  hostname: lab.sethlakowske.com
  
  # Set default security context for all containers
  securityContext:
    runAsUser: 1000     # Developer UID
    runAsGroup: 1000    # Developer GID
    fsGroup: 1000       # Files created belong to developer group
    fsGroupChangePolicy: "OnRootMismatch"
  
  restartPolicy: Always
  
  # Init container to set up permissions
  initContainers:
  - name: permission-setup
    image: localhost/podserve-base:latest
    securityContext:
      runAsUser: 0  # Must run as root to change ownership
    command:
    - /bin/bash
    - -c
    - |
      echo "Setting up permissions for developer access..."
      
      # Ensure directories exist
      mkdir -p /data/{config,logs,state,web,mail}
      
      # Set ownership to developer user and group
      chown -R 1000:1000 /data
      
      # Set permissions: owner and group can read/write
      chmod -R 755 /data
      
      # Set setgid bit so new files inherit group
      find /data -type d -exec chmod g+s {} \;
      
      echo "Permissions setup complete"
    volumeMounts:
    - name: podserve-data
      mountPath: /data
  
  containers:
  
  # Apache container - can run as developer for most operations  
  - name: apache
    image: localhost/podserve-apache:latest
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add:
        - NET_BIND_SERVICE  # Allow binding to ports 80/443
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    env:
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    volumeMounts:
    - name: podserve-data
      mountPath: /data
    - name: podserve-src
      mountPath: /opt/podserve
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      
  # Mail container - needs root for privileged ports
  - name: mail
    image: localhost/podserve-mail:latest
    securityContext:
      runAsUser: 0  # Must run as root for mail services
      runAsGroup: 0
    ports:
    - containerPort: 25
      protocol: TCP
    - containerPort: 587  
      protocol: TCP
    - containerPort: 143
      protocol: TCP
    - containerPort: 993
      protocol: TCP
    - containerPort: 995
      protocol: TCP
    env:
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    volumeMounts:
    - name: podserve-data
      mountPath: /data
    - name: podserve-src
      mountPath: /opt/podserve
    livenessProbe:
      tcpSocket:
        port: 25
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 25
      initialDelaySeconds: 10
      periodSeconds: 5
      
  # DNS container - can run as developer with capabilities
  - name: dns
    image: localhost/podserve-dns:latest
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add:
        - NET_BIND_SERVICE  # Allow binding to port 53
    ports:
    - containerPort: 53
      protocol: TCP
    - containerPort: 53
      protocol: UDP
    env:
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    volumeMounts:
    - name: podserve-data
      mountPath: /data
    - name: podserve-src
      mountPath: /opt/podserve
    livenessProbe:
      exec:
        command:
        - /usr/local/bin/health-check.sh
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - /usr/local/bin/health-check.sh
      initialDelaySeconds: 5
      periodSeconds: 5
  
  volumes:
  
  # Persistent data volume
  - name: podserve-data
    persistentVolumeClaim:
      claimName: podserve-data
      
  # Host-mounted source code for development
  - name: podserve-src
    hostPath:
      path: ./src/podserve
      type: Directory