apiVersion: v1
kind: Pod
metadata:
  name: podserve-python-webmail
  labels:
    app: podserve
    implementation: python-unified
spec:
  containers:
  # Apache Web Server
  - name: apache
    image: localhost/podserve-apache:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: apache-health
    env:
    - name: APACHE_SERVER_NAME
      value: "web.lab.localhost"
    - name: APACHE_SERVER_ADMIN
      value: "webmaster@lab.localhost"
    - name: APACHE_DOCUMENT_ROOT
      value: "/data/web/html"
    - name: CERT_MODE
      value: "self-signed"
    - name: LOG_LEVEL
      value: "INFO"
    volumeMounts:
    - name: web-data
      mountPath: /data/web
    - name: logs
      mountPath: /data/logs
    - name: config
      mountPath: /data/config
    - name: state
      mountPath: /data/state
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  
  # Mail Server
  - name: mail
    image: localhost/podserve-mail:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 25
      hostPort: 25
      name: smtp
    - containerPort: 143
      hostPort: 143
      name: imap
    - containerPort: 587
      hostPort: 587
      name: submission
    - containerPort: 993
      hostPort: 993
      name: imaps
    - containerPort: 995
      hostPort: 995
      name: pop3s
    - containerPort: 8081
      hostPort: 8081
      name: mail-health
    env:
    - name: MAIL_SERVER_NAME
      value: "mail.lab.localhost"
    - name: MAIL_DOMAIN
      value: "lab.localhost"
    - name: MAIL_DATA_DIR
      value: "/var/mail/vhosts"
    - name: CERT_MODE
      value: "self-signed"
    - name: LOG_LEVEL
      value: "INFO"
    - name: HEALTH_CHECK_PORT
      value: "8081"
    volumeMounts:
    - name: mail-data
      mountPath: /var/mail
    - name: logs
      mountPath: /data/logs
    - name: config
      mountPath: /data/config
    - name: state
      mountPath: /data/state
    livenessProbe:
      httpGet:
        path: /health
        port: 8081
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 5

  volumes:
  - name: web-data
    emptyDir: {}
  - name: mail-data
    emptyDir: {}
  - name: logs
    emptyDir: {}
  - name: config
    emptyDir: {}
  - name: state
    emptyDir: {}
  restartPolicy: Always