apiVersion: v1
kind: Pod
metadata:
  name: podserve-simple
  labels:
    app: podserve
    environment: simple
spec:
  hostname: lab.sethlakowske.com
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "lab.sethlakowske.com"
  containers:
  - name: apache
    image: localhost/podserve-apache:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    env:
    - name: APACHE_SERVER_NAME
      value: "lab.sethlakowske.com"
    - name: APACHE_SERVER_ADMIN
      value: "lakowske@gmail.com"
    - name: SSL_ENABLED
      value: "auto"
    - name: WEBDAV_ENABLED
      value: "true"
    - name: GITWEB_ENABLED
      value: "true"
    volumeMounts:
    - name: web
      mountPath: /data/web
    - name: certificates
      mountPath: /data/state/certificates
      readOnly: true
  - name: mail
    image: localhost/podserve-mail:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 25
      hostPort: 25
    - containerPort: 143
      hostPort: 143
    - containerPort: 993
      hostPort: 993
    - containerPort: 587
      hostPort: 587
    - containerPort: 995
      hostPort: 995
    env:
    - name: MAIL_SERVER_NAME
      value: "mail.lab.sethlakowske.com"
    - name: MAIL_DOMAIN
      value: "lab.sethlakowske.com"
    volumeMounts:
    - name: certificates
      mountPath: /data/state/certificates
      readOnly: true
    - name: mail
      mountPath: /var/mail/vhosts
  - name: dns
    image: localhost/podserve-dns:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 53
      hostPort: 53
      protocol: UDP
    - containerPort: 53
      hostPort: 53
      protocol: TCP
    env:
    - name: DNS_FORWARDERS
      value: "8.8.8.8;8.8.4.4"
    - name: DNSSEC_ENABLED
      value: "no"
  volumes:
  - name: web
    persistentVolumeClaim:
      claimName: podserve-simple-web
  - name: mail
    persistentVolumeClaim:
      claimName: podserve-simple-mail
  - name: certificates
    persistentVolumeClaim:
      claimName: podserve-certificates
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podserve-simple-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podserve-simple-mail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
